"use client";
// import type { Metadata } from "next";
import Providers from "./styling/theme/Providers";
import Navbar from "./components/Navbar/navbar";
import MarketDataBar from "./components/Navbar/MarketDataBar";
import StoreProvider from "./StoreProvider";
import SliderButton from "./components/Converter/SliderButton";
import { usePathname } from "next/navigation";
import { spaceGrotesk } from "./styling/theme/font";
import useWindowSize from "./useWindowSize";

// export const metadata: Metadata = {
//   title: "Crypto App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const { width } = useWindowSize();

  return (
    <html lang="en">
      <body className={spaceGrotesk.className}>
        <StoreProvider>
          <Providers>
            {width >= 767 ? (
              <>
                <MarketDataBar />
                <Navbar />
              </>
            ) : (
              <>
                <Navbar />
                <MarketDataBar />
              </>
            )}
            {pathname === "/" || pathname === "/converter" ? (
              <SliderButton />
            ) : null}
            {children}
          </Providers>
        </StoreProvider>
      </body>
    </html>
  );
}
