"use client";
// import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import Providers from "./styling/theme/Providers";
import Navbar from "./components/Navbar/navbar";
import MarketDataBar from "./components/Navbar/MarketDataBar";
import StoreProvider from "./StoreProvider";
import SliderButton from "./components/Converter/SliderButton";

const spaceGrotesk = Space_Grotesk({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Crypto App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={spaceGrotesk.className}>
        <StoreProvider>
          <Providers>
            <MarketDataBar />
            <Navbar />
            <SliderButton />
            {children}
          </Providers>
        </StoreProvider>
      </body>
    </html>
  );
}
